### ISSUE TITLE
How do I add this?

### ISSUE THREAD

**Issue by michaeldsim** [ExidCuter/Fortnite4J#1]
This is a noob question but how do I add this to my project in Eclipse?
I'm new to this and I've only ever dealt with adding things via Gradle and Maven. I try to add the .jar and attach the source but the stuff from the org.json package says that I need to change the source to view the source code for that.

**Comment by ExidCuter** [comment]
Currently I have no Maven or Gradle repo set up. So you have to add the .jar file. 

I have no experience with Eclipse I mainly use InteliJ IDEA, but Google to the rescue [How to add a .jar file to Eclipse](https://stackoverflow.com/questions/3280353/how-to-import-a-jar-in-eclipse). 

And if you are using gradle to build your project just add this line to the dependencies: `compile files('./yourLibFolder/Fortnite4J.jar')` to your `build.gradle` file. 

PS: The `.jar` file is located in the root of the GitHub project. And you should know that this lib is in it's very early stages and will probably stay there. (I have very little time) but feel free to add or change anything. 

Hope this helps.
